### ISSUE TITLE
Link to Urls does not open!!!

### ISSUE THREAD

**Issue by szm2015** [openimages/dataset#17]
Hi everyone 
I tried to download the image urls via [Image URLs and metadata](https://storage.googleapis.com/openimages/2016_08/images_2016_08_v5.tar.gz) but when I click on it I get this:
![openimage](https://cloud.githubusercontent.com/assets/16157023/20148953/442dcbc4-a6c4-11e6-9a9a-1ffe1d7021b4.png)

And when I try to download via uget, right click ... but the link seems to be damaged. I appreciate any help.

**Comment by gkrasin** [comment]
Hm... In which country is the computer that you use to download the data? The error message looks very strange:

```
We're sorry, but this service is not available in your location
```

**Comment by szm2015** [comment]
OK, I got it, I guess it's because I'm in Iran, nice of google to filter us like this ...

**Comment by gkrasin** [comment]
Sorry. Obviously, we (the team behind the OpenImages dataset) would like to make it available in Iran, and also other countries from which it is inaccessible. As you can imagine, there are bureaucratic and technical issues involved in doing that, so it will take time. We are doing what we can.

I'm going to lock this issue to further comments, since there is nothing more I can say about these issues.
