### ISSUE TITLE
Importing Graph

### ISSUE THREAD

**Issue by AdityaChaganti** [openimages/dataset#21]
@gkrasin, is there a way to easily import the graphdef and weights of the net trained on OpenImages? I try to import the graph from the model.ckpt.meta file as described [here](https://www.tensorflow.org/versions/r0.11/how_tos/meta_graph/index.html), but I run into a SSTableReader KeyError.

**Comment by gkrasin** [comment]
@AdityaChaganti I will look into this. No promises on that being quick, but it's a recurrent request, so it feels like worth doing.

If someone has cycles to do it before I started, a help is appreciated, see the [contribution guidelines](https://github.com/openimages/dataset/blob/master/CONTRIBUTING.md).

**Comment by AdityaChaganti** [comment]
@gkrasin Thank you!
The need to do this, as far as I'm concerned, is due to the time that tf slim takes to load inception v3. It also seems to append the image data to the architecture while doing this. I would ideally want to load the network independently of my image data. My understanding is that loading the graph using [import_meta_graph](https://www.tensorflow.org/versions/r0.11/how_tos/meta_graph/index.html) is faster, and therefore more useful when running inference over multiple images.

**Comment by gkrasin** [comment]
I have a feel that you have been working with an older version of [classify.py](https://github.com/openimages/dataset/blob/master/tools/classify.py) script. Just recently I added an ability to run the script on multiple images, and since I didn't want to complicate the code with TensorFlow queues, I started to use placeholders instead of the real data as the input. While the code is not ideal (for instance, it does not batch inputs), it does not load the network for each input either.

Does it help you in the interim?

**Comment by AdityaChaganti** [comment]
I was working on a modified older version, yes. I'll integrate that into my code and get back to you on performance. It does sound like that should work for the time being, though.

**Comment by AdityaChaganti** [comment]
@gkrasin This works as expected.

**Comment by revilokeb** [comment]
@AdityaChaganti, @gkrasin  I am on TF 0.12.1 (GPU) and also tried to get some info on the graph of the pre-trained inception v3 on openimages by just trying to load it:
```
import tensorflow as tf
with tf.Session() as sess:
    saver = tf.train.import_meta_graph('/PATH_TO/2016_08/model.ckpt.meta')
```

I am obtaining the same error 
> KeyError: u'SSTableReader'

The way to circumvent seems to assume the graph structure as in [classify.py](https://github.com/openimages/dataset/blob/master/tools/classify.py)? i.e. 
```
with slim.arg_scope(inception.inception_v3_arg_scope()):
      logits, end_points = inception.inception_v3(
          processed_image, num_classes=FLAGS.num_classes, is_training=False)

    predictions = end_points['multi_predictions'] = tf.nn.sigmoid(logits, name='multi_predictions')
```
However, from your above comments I dont understand, _why_ this really is happening since the meta graph probably got created using some statement such as 
`meta_graph_def = tf.train.export_meta_graph(filename='/PATH_TO/2016_08/my-model.meta')`

Or is this some incompatibility between TF 0.12.1 (which I am on) and a previous version of TF that was used to create the meta graph of the pre-trained model?

**Comment by AdityaChaganti** [comment]
@revilokeb I never got around this issue, and am curious about why it happens as well. Just in case you're interested, though, my workaround to this was to import the graph structure as done in [classify.py](https://github.com/openimages/dataset/blob/master/tools/classify.py). I first dump that into my file system as a protobuf file using the [freeze graph](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) method, and then combine this graphdef with the weights from the .ckpt file that's downloaded along with the meta.

**Comment by gkrasin** [comment]
@revilokeb the training was performed using the SSTableReader (an internal variant of [LevelDB](https://en.wikipedia.org/wiki/LevelDB)) and that's why it probably happens when ```import_meta_graph``` is called.

I think that the way to go is what @AdityaChaganti has described. Next time I will be more careful when I release the net, as it's clear that this internal-only leftover causing quite a bit of frustration (sorry!)

**Comment by sxs4337** [comment]
I also get this error while loading the meta graph-
ValueError: No op named SSTableReader in defined operations.

@AdityaChaganti 
Can you please point to a script that does the workaround?
Thanks a lot!

**Comment by sxs4337** [comment]
Update- I was able to do convert the model to pb using this short script. (same as suggestion above)

```
import tensorflow as tf
from tensorflow.contrib.slim.python.slim.nets import inception
from tensorflow.python.training import saver as tf_saver
from tensorflow.python.framework import graph_util
slim = tf.contrib.slim

input_checkpoint = 'model.ckpt'
output_file = 'inference_graph.pb'

g = tf.Graph()
with g.as_default():
    image = tf.placeholder(name='input', dtype=tf.float32, shape=[1, 299, 299, 3])
    with slim.arg_scope(inception.inception_v3_arg_scope()):
        logits, end_points = inception.inception_v3(image, num_classes=6012, is_training=False)
        predictions = tf.nn.sigmoid(logits, name='multi_predictions')
        saver = tf_saver.Saver()
        input_graph_def = g.as_graph_def()
        sess = tf.Session()
        saver.restore(sess, input_checkpoint)

        output_node_names = "multi_predictions"
        output_graph_def = graph_util.convert_variables_to_constants(
            sess, # The session is used to retrieve the weights
            input_graph_def, # The graph_def is used to retrieve the nodes 
            output_node_names.split(",") # The output node names are used to select the usefull nodes
        )
        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_file, "wb") as f:
            f.write(output_graph_def.SerializeToString())
```
